### ISSUE TITLE
Use the project for other swap 

### ISSUE THREAD

**Issue by ronezra3** [monosux/uniprices#12]
Hey, thank you so much for the super cool project!

Is it possible to make code modifications to use this tool for other swaps, that are Uniswap forks?

What needs to be modified for it?

Thanks :)

**Comment by monosux** [comment]
Hi @ronezra3,

The code could be modified for sure! But note, the package works with the uniswap v1 protocol. It is kind of outdated. And I believe the current version of the protocol is v3. For now, I don't have any plans to update the package.
